import { StaticDecode, Type } from "@sinclair/typebox";
import { SupportedCustomEvents, SupportedEvents } from "./context";

const sharedSchema = Type.Object({
    stateId: Type.String({
        description: "The session ID for the server (generated by the kernel as stateId)",
    }),
    authToken: Type.String({
        description: "The authentication token sent by the kernel to the worker",
    }),
    ref: Type.String({
        description: "The ref sent by the kernel to the worker",
    }),
    sessionId: Type.String({
        description: "The session ID for the server (generated by the kernel as stateId)",
    }),
    workflowId: Type.Number({
        description: "The workflow run ID of the current running server that needs to be restarted",
    }),
    command: Type.String({
        description: "The command sent by the kernel to the worker",
    }),
    signature: Type.String({
        description: "The signature sent by the kernel to the worker",
    }),
});

const serverStartSchema = Type.Object({
    action: Type.Literal("server.start"),
    client_payload: sharedSchema,
});

const serverRestartSchema = Type.Object({
    action: Type.Literal("server.restart"),
    client_payload: sharedSchema,
});


const serverStopSchema = Type.Object({
    action: Type.Literal("server.stop"),
    client_payload: sharedSchema,
});

export const customEventSchemas = {
    "server.start": serverStartSchema,
    "server.restart": serverRestartSchema,
    "server.stop": serverStopSchema,
} as const

export type CustomEventSchemas<T extends SupportedCustomEvents> = 
    T extends keyof typeof customEventSchemas ? StaticDecode<typeof customEventSchemas[T]> : never;